twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        image_directory: '%image_directory%'
        websiteService: '@App\Service\Website\WebsiteService'

when@test:
    twig:
        strict_variables: true
