vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        images:
            uri_prefix: /assets/medias/images
            upload_destination: '%kernel.project_dir%/public/assets/medias/images'
            namer: vich_uploader.namer_uniqid
            delete_on_update: false
            delete_on_remove: true
        picturesProfileImages:
            uri_prefix: /assets/images/picturesProfile
            upload_destination: '%kernel.project_dir%/public/assets/images/picturesProfile'
            namer: vich_uploader.namer_uniqid
            delete_on_update: false
            delete_on_remove: true
