vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        images:
            uri_prefix: /assets/images/medias
            upload_destination: '%kernel.project_dir%/public/assets/images/medias'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true
